title: EcoClassify
theme: minima
description: EcoClassify SyncroSim package
author: Apex Resource Management Solutions
email: info@apexrms.com
header_pages:
  - index.md
  - getting_started.md
collections:
  project:
    output: true
  scenarios:
    output: true
