title: geofetch
theme: minima
description: geofetch SyncroSim package
author: Apex Resource Management Solutions
email: info@apexrms.com
header_pages:
  - index.md
  - getting_started.md
  - tutorials.md
  - reference.md
collections:
  project:
    output: true
  scenarios:
    output: true
